---
swagger: "2.0"
info:
  description: "REST api exposing video entities"
  version: "2.0"
  title: "Microservice: Video"
  contact:
    name: "Jose David Baena"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"
host: "localhost:8080"
basePath: "/"
tags:
- name: "video-controller"
  description: "Video Controller"
paths:
  /api/videos:
    get:
      tags:
      - "video-controller"
      summary: "getVideos"
      operationId: "getVideosUsingGET"
      consumes:
      - "application/json"
      produces:
      - "*/*"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Video"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
    post:
      tags:
      - "video-controller"
      summary: "storeVideo"
      operationId: "storeVideoUsingPOST"
      consumes:
      - "application/json"
      produces:
      - "*/*"
      parameters:
      - in: "body"
        name: "videos"
        description: "videos"
        required: true
        schema:
          $ref: "#/definitions/Video"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Video"
        201:
          description: "Created"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
  /api/videos/{id}:
    get:
      tags:
      - "video-controller"
      summary: "getVideoById"
      operationId: "getVideoByIdUsingGET"
      consumes:
      - "application/json"
      produces:
      - "*/*"
      parameters:
      - name: "id"
        in: "path"
        description: "id"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Video"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
    put:
      tags:
      - "video-controller"
      summary: "updateVideo"
      operationId: "updateVideoUsingPUT"
      consumes:
      - "application/json"
      produces:
      - "*/*"
      parameters:
      - name: "id"
        in: "path"
        description: "id"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "video"
        description: "video"
        required: true
        schema:
          $ref: "#/definitions/Video"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/Video"
        201:
          description: "Created"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"
    delete:
      tags:
      - "video-controller"
      summary: "deleteVideo"
      operationId: "deleteVideoUsingDELETE"
      consumes:
      - "application/json"
      produces:
      - "*/*"
      parameters:
      - name: "id"
        in: "path"
        description: "id"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "OK"
        204:
          description: "No Content"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
definitions:
  Video:
    properties:
      description:
        type: "string"
      id:
        type: "integer"
        format: "int64"
      identifier:
        type: "string"
      provider:
        type: "string"
      title:
        type: "string"
